# Build settings
markdown: redcarpet
highlighter: pygments
  
# Site settings
title: "Mind about JavaScript"
description: > # this means to ignore newlines until "email:"
   how not to get lost amongst JS lines of code

email: mintaboutjs@gmail.com
# blog cover
cover: "/assets/images/home-splash.jpg"

name: 'Mind about JavaScript'

paginate:	5

url: "http://mindaboutjs.com" # the base hostname & protocol for your site
baseurl: ""

# social icons and sharing options
social:

  - icon:	envelope-o
    url:	mailto:mindaboutjs@gmail.com
    desc:	Contact me
    share_url:
    share_title:
    share_link:
